// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-aBu4fKzs1rFUAZpYhvWb_36NoMXN1k',
    appId: '1:719047798352:web:296d6b3e29bac9617deb55',
    messagingSenderId: '719047798352',
    projectId: 'gifttracker-c8f01',
    authDomain: 'gifttracker-c8f01.firebaseapp.com',
    storageBucket: 'gifttracker-c8f01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFx7YOgP8ohnqPYeLYiaB6wrLW8jgJzC8',
    appId: '1:719047798352:android:e41d36db00cf47327deb55',
    messagingSenderId: '719047798352',
    projectId: 'gifttracker-c8f01',
    storageBucket: 'gifttracker-c8f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoEvEqiPH93zHo_nNgjtHfUrZfX9sHaqk',
    appId: '1:719047798352:ios:c14038cb83315ce57deb55',
    messagingSenderId: '719047798352',
    projectId: 'gifttracker-c8f01',
    storageBucket: 'gifttracker-c8f01.firebasestorage.app',
    iosBundleId: 'com.example.trackerss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoEvEqiPH93zHo_nNgjtHfUrZfX9sHaqk',
    appId: '1:719047798352:ios:c14038cb83315ce57deb55',
    messagingSenderId: '719047798352',
    projectId: 'gifttracker-c8f01',
    storageBucket: 'gifttracker-c8f01.firebasestorage.app',
    iosBundleId: 'com.example.trackerss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF-aBu4fKzs1rFUAZpYhvWb_36NoMXN1k',
    appId: '1:719047798352:web:62053bac75faca507deb55',
    messagingSenderId: '719047798352',
    projectId: 'gifttracker-c8f01',
    authDomain: 'gifttracker-c8f01.firebaseapp.com',
    storageBucket: 'gifttracker-c8f01.firebasestorage.app',
  );
}
